<?php
/**
 * Template Name: Search Page Template
 * Template Post Type: post, page
 *
 * @package WordPress
 */
get_header();
?>
<header>
<link href="https://fonts.googleapis.com/css?family=Material+Icons" rel="stylesheet">

</header>
<div class="wrap">
	<div id="primary" class="content-area">
		<main id="main" class="site-main" role="main">
			<div id="wp-vue-app">
				This text will be replaced by the Vue App when the SPA build (generated by Webpack) is enqueued in WordPress.
			</div><!-- #vue-app -->
		</main><!-- #main -->
	</div><!-- #primary -->
</div><!-- .wrap -->

<?php
get_footer();